workspace:
  base: /srv/app
  path: src/github.com/go-gitea/lgtm

pipeline:
  test:
    image: webhippie/golang:edge
    pull: true
    environment:
      CGO_ENABLED: 1
    commands:
      - make clean
      - make vet
      - make lint
      - make test
      - make build

  mysql:
    image: webhippie/golang:edge
    pull: true
    commands:
     - make test-mysql
    when:
      event: push

  pgsql:
    image: webhippie/golang:edge
    pull: true
    commands:
     - make test-pgsql
    when:
      event: push

  updater:
    image: karalabe/xgo-latest:latest
    pull: true
    commands:
      - make publish
    when:
      event: [ push, tag ]
      branch: [ master, refs/tags/* ]

  coverage:
    image: plugins/coverage
    server: http://coverage.dronehippie.de

  docker1:
    image: plugins/docker
    repo: gitea/lgtm
    tags: [ '${TAG}' ]
    when:
      event: tag
      branch: refs/tags/*

  docker2:
    image: plugins/docker
    repo: gitea/lgtm
    tags: [ 'latest' ]
    when:
      event: push
      branch: master

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  pgsql:
    image: postgres:9.5
    environment:
      - POSTGRES_DB=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
